<?php

namespace nst\messages;

/**
 * NstPushNotificationTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NstPushNotificationTemplateRepository extends \sacore\application\DefaultRepository
{
}
