<?php

namespace nst\messages;

use sa\messages\pushNotificationRepository;

/**
 * NstPushNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NstPushNotificationRepository extends pushNotificationRepository
{
  public function markAllNotificationsAsRead($nurse_id)
  {
    return $this->createQueryBuilder('notification')
      ->update()
      ->set('notification.is_read', true)
      ->where('notification.nurse = :nurse_id')
      ->setParameter(':nurse_id', $nurse_id)
      ->getQuery()
      ->getSingleScalarResult();
  }
}
