<?php

namespace nst\applications;

/**
 * Application1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Application1Repository extends \sacore\application\DefaultRepository
{

    public function manageApplications()
    {
        $query = $this->createQueryBuilder('q')
            ->select('q.id as applicant_id, m.id as member_id, m.first_name, m.last_name, n.username, q.phone_number, q.city, q.state,
            q.submitted_at, q.approved_at, q.declined_at, s.is_active, s.last_active, s.application_submitted,
            s.license_submitted, s.license_verified, s.files_submitted, s.drug_screen_status, s.drug_screen_scheduled_date,
            s.drug_screen_accepted, s.background_check_started_date, s.background_check_status,
            s.background_check_accepted', 's.background_check_signed_time', 's.drug_screen_report')
            ->innerJoin('q.member', 'm')
            ->innerJoin('m.application_part2', 'a')
            ->innerJoin('a.application_status', 's')
            ->innerJoin('m.users', 'n');

        return $query->getQuery()->getResult();
    }
}
