<?php

namespace nst\applications;

/**
 * Application2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Application2Repository
{
}