<?php

namespace nst\applications;

/**
 * ApplicationStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationStatusRepository
{
}