<?php

namespace nst\applications;

/**
 * NurseBackgroundCheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurseBackgroundCheckRepository extends \sacore\application\DefaultRepository
{
}
