<?php

namespace nst\member;

/**
 * NurseApplicationPartTwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurseApplicationPartTwoRepository extends \sacore\application\DefaultRepository
{
}
