<?php

namespace sa\messages;

use Doctrine\ORM\EntityRepository;

/**
 * saSMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saSMSRepository extends \sacore\application\DefaultRepository
{

    public function getNewCount( $batch_id=null ) {
        $qb = $this->createQueryBuilder('m');
        $qb->select('COUNT(m)');
        $qb->where('m.attempted_send = 0');
        if ($batch_id) {
            $qb->andWhere('m.batch_id = :batch_id');
            $qb->setParameter(':batch_id', $batch_id);
        }
        else
        {
            $qb->andWhere('m.batch_id is null');
        }
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getNew( $batch_id=null, $limit=50, $offset=0 ) {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.attempted_send = 0');
        if ($batch_id) {
            $qb->andWhere('m.batch_id = :batch_id');
            $qb->setParameter(':batch_id', $batch_id);
        }
        else
        {
            $qb->andWhere('m.batch_id is null');
        }
        $qb->setMaxResults($limit);
        $qb->setFirstResult($offset);
        return $qb->getQuery()->getResult();
    }
    
}
