<?php

namespace sa\messages;

use Doctrine\ORM\EntityRepository;

/**
 * saVoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saVoiceRepository extends \sacore\application\DefaultRepository
{

   

}
