<?php

namespace nst\payroll;

/**
 * PayrollItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayrollItemsRepository extends \sacore\application\DefaultRepository
{
}
