<?php

namespace sa\system;

/**
 * saCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saCityRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCityByState($state) {

        $query = $this->createQueryBuilder('q');

        $query->join('q.county', 'c')
                ->join('c.state', 's')
                ->where('s.id=:state')
                ->setParameter(':state', $state->getId())
                ->orderBy('q.name', 'ASC');

        return $query->getQuery()->getResult();
    }

}
