<?php

namespace sa\system;

/**
 * saClusterNodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saClusterNodesRepository extends \sacore\application\DefaultRepository
{
}
