<?php

namespace sa\system;

/**
 * saCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saCountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCountry($data = array()) {

        $r = null;
        if ( !empty($data) ) {
            $q = $this->createQueryBuilder('a')
                ->select('a')
                ->where('a.name IN (:country)')
                ->setParameter(':country', $data);
            $q->orderBy('a.name', 'ASC');

            //echo $q->getQuery()->getSQL();exit;

            try {
                $r = $q->getQuery()->getResult(); // return hydrated object
            }
            catch(NoResultException $e) {

            }
        }

        return $r;
    }

    public function findCountryByNameIdAbbr( $string ) {

        $q = $this->createQueryBuilder('a')
            ->where( 'a.id = :search' )
            ->orWhere( 'a.name = :search' )
            ->orWhere( 'a.abbreviation = :search' )
            ->setParameter(':search', $string);

        return $q->getQuery()->getOneOrNullResult();

    }


}