<?php

namespace sa\system;

/**
 * saStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saStateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCountryStates( $id = 0 ) {
        $r = null;
        if ( $id ) {
            $q = $this->createQueryBuilder('a')
                ->select('a.id, a.name')
                ->join( 'a.country', 'c' )
                ->where('c.id = :country_id')
                ->setParameter(':country_id', $id);

            //echo $q->getQuery()->getSQL();exit;

            try {
                $r = $q->getQuery()->getResult(); // return hydrated object
            }
            catch(NoResultException $e) {

            }
        }
        return $r;
    }


    public function findStateByNameIdAbbr( $string ) {
      $q = $this->createQueryBuilder('a')
            ->where( 'a.id = :search' )
            ->orWhere( 'a.name = :search' )
            ->orWhere( 'a.abbreviation = :search' )
            ->setParameter(':search', $string)
            // TODO : This is a temporary fix; Doctrine can sometimes throw a 
            // TODO : NonUniqueResultException even when the query returns a single result. - kcarter
            ->setMaxResults(1); 

        return $q->getQuery()->getOneOrNullResult();
    }


}
