<?php

namespace sa\system;

use sacore\application\DefaultRepository;

/**
 * saUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saUserLoginActivityRepository extends DefaultRepository
{
    public function searchByUser($user, $orderBy=null, $perPage=null, $offset=null, $count = false, $secondary_sort=null, $where_andor = 'and') {
        $query = $this->createQueryBuilder('q');

        if ($orderBy) {
            foreach($orderBy as $f=>$d) {
                $query->addOrderBy('q.'.$f, $d);
            }
        }

        if ($secondary_sort) {
            foreach($secondary_sort as $f=>$d) {
                $query->addOrderBy('q.'.$f, $d);
            }
        }

        if ($perPage) {
            $query->setMaxResults($perPage);
        }

        if ($offset) {
            $query->setFirstResult($offset);
        }


        $query->andWhere('q.user = :user');
        $query->setParameter(':user', $user);


        if($count) {
            $query->select('count(q.id)');
            return $query->getQuery()->getSingleScalarResult();
        }
        else
            return $query->getQuery()->getResult();
    }

    /**
     * @param saUser $user
     * @return array
     */
    public function getUniqueLoginsByIp($user)
    {
        $q = $this->createQueryBuilder('activity');

        $q->select('activity.ip_address');
        $q->distinct();
        $q->where('activity.user = :user');
        $q->setParameter(':user', $user);

        return $q->getQuery()->getArrayResult();
    }
}
