<?php
namespace sa\system;

use Doctrine\ORM\EntityRepository;
use sacore\application\app;
use sacore\application\moduleConfig;

/**
 * saUserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saUserGroupRepository extends \sacore\application\DefaultRepository
{
}
