<?php

namespace sa\system;
use sacore\application\app;
use sacore\application\DefaultRepository;

/**
 * saUserPushTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saUserPushTokenRepository extends DefaultRepository
{
    /**
     * @param saUser $user
     * @return array
     */
    public function getAllForUser(saUser $user) {
        return $this->findBy(array('user' => $user));
    }
}
