<?php

namespace sa\member;

use Doctrine\ORM\EntityRepository;

/**
 * saMemberEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saMemberEmailRepository extends EntityRepository
{



}
