<?php

namespace sa\member;

use Doctrine\ORM\EntityRepository;
use sacore\application\DefaultRepository;

/**
 * saMemberUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saMemberUsersRepository extends DefaultRepository
{
    public function search($fieldsToSearch, $orderBy=null, $perPage=null, $offset=null, $count = false, $secondary_sort=null, $where_andor = 'and', $search_start = true, $search_end = true) {
        $query = $this->createQueryBuilder('q');

        if ($orderBy) {
            foreach($orderBy as $f => $d) {
                if($f == 'company') {
                    $query->join('q.member', 'member');
                    $query->addOrderBy('member.company', $d);
                } else {
                    $query->addOrderBy('q.'.$f, $d);
                }
            }
        }

        if ($secondary_sort) {
            foreach($secondary_sort as $f=>$d) {
                $query->addOrderBy('q.'.$f, $d);
            }
        }

        if ($perPage) {
            $query->setMaxResults($perPage);
        }

        if ($offset) {
            $query->setFirstResult($offset);
        }
        
        if (is_array($fieldsToSearch) ) {
            foreach ($fieldsToSearch as $f => $v) {
                if($where_andor == 'or') {
                    $query->orWhere('q.' . $f . ' LIKE :' . $f);
                } else {
                    $query->andWhere('q.' . $f . ' LIKE :' . $f);
                }

                $query->setParameter(':' . $f, ($search_start ? '%' : '') . $v . ($search_end ? '%' : ''));
            }
        }

        if($count) {
            $query->select('count(q.id)');
            return $query->getQuery()->getSingleScalarResult();
        }
        else {
            return $query->getQuery()->getResult();
        }
    }
}
