<?php

namespace sa\member;

use Doctrine\ORM\EntityRepository;

/**
 * saMemberGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saMemberGroupRepository extends \sacore\application\DefaultRepository
{

}
