<?php

namespace sa\events;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \sacore\application\DefaultRepository
{
}
