<?php

namespace sa\events;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \sacore\application\DefaultRepository
{
}
