<?php

namespace sa\developer;

use Doctrine\ORM\EntityRepository;

/**
 * saExtModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saExtModuleRepository extends EntityRepository
{
}
