<?php

namespace sa\developer;

use Doctrine\ORM\EntityRepository;

/**
 * saUnitTestingLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saUnitTestingLogRepository extends EntityRepository
{
    public function getRecent($number = 5)
    {
        $dql = "SELECT l FROM sa\developer\saUnitTestingLog l ORDER BY l.id DESC";
//        $query = $this->createQueryBuilder("l");
//        $query->orderBy("l.id", "DESC");
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setMaxResults($number);

        return $query->getResult();
    }

    public function getLog($test_num, $assertions_num, $failed_num, $date = null)
    {
        if (! date) {
            $date = date('Y-m-d');
        }

        $dql = "SELECT l FROM sa\developer\saUnitTestingLog l WHERE l.test_num=:test AND l.assertions_num=:assertions AND l.failed_num=:failed and l.test_time>=:time";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameters(['test' => $test_num, 'assertions' => $assertions_num, 'failed' => $failed_num, 'time' => $date]);
        $query->setMaxResults(1);

        return $query->getResult();
    }
}
