INSERT INTO `sa_states` VALUES ('1', 'AL', 'Alabama');
INSERT INTO `sa_states` VALUES ('2', 'AK', 'Alaska');
INSERT INTO `sa_states` VALUES ('3', 'AZ', 'Arizona');
INSERT INTO `sa_states` VALUES ('4', 'AR', 'Arkansas');
INSERT INTO `sa_states` VALUES ('5', 'CA', 'California');
INSERT INTO `sa_states` VALUES ('6', 'CO', 'Colorado');
INSERT INTO `sa_states` VALUES ('7', 'CT', 'Connecticut');
INSERT INTO `sa_states` VALUES ('8', 'DE', 'Delaware');
INSERT INTO `sa_states` VALUES ('9', 'DC', 'District of Columbia');
INSERT INTO `sa_states` VALUES ('10', 'FL', 'Florida');
INSERT INTO `sa_states` VALUES ('11', 'GA', 'Georgia');
INSERT INTO `sa_states` VALUES ('12', 'HI', 'Hawaii');
INSERT INTO `sa_states` VALUES ('13', 'ID', 'Idaho');
INSERT INTO `sa_states` VALUES ('14', 'IL', 'Illinois');
INSERT INTO `sa_states` VALUES ('15', 'IN', 'Indiana');
INSERT INTO `sa_states` VALUES ('16', 'IA', 'Iowa');
INSERT INTO `sa_states` VALUES ('17', 'KS', 'Kansas');
INSERT INTO `sa_states` VALUES ('18', 'KY', 'Kentucky');
INSERT INTO `sa_states` VALUES ('19', 'LA', 'Louisiana');
INSERT INTO `sa_states` VALUES ('20', 'ME', 'Maine');
INSERT INTO `sa_states` VALUES ('21', 'MD', 'Maryland');
INSERT INTO `sa_states` VALUES ('22', 'MA', 'Massachusetts');
INSERT INTO `sa_states` VALUES ('23', 'MI', 'Michigan');
INSERT INTO `sa_states` VALUES ('24', 'MN', 'Minnesota');
INSERT INTO `sa_states` VALUES ('25', 'MS', 'Mississippi');
INSERT INTO `sa_states` VALUES ('26', 'MO', 'Missouri');
INSERT INTO `sa_states` VALUES ('27', 'MT', 'Montana');
INSERT INTO `sa_states` VALUES ('28', 'NE', 'Nebraska');
INSERT INTO `sa_states` VALUES ('29', 'NV', 'Nevada');
INSERT INTO `sa_states` VALUES ('30', 'NH', 'New Hampshire');
INSERT INTO `sa_states` VALUES ('31', 'NJ', 'New Jersey');
INSERT INTO `sa_states` VALUES ('32', 'NM', 'New Mexico');
INSERT INTO `sa_states` VALUES ('33', 'NY', 'New York');
INSERT INTO `sa_states` VALUES ('34', 'NC', 'North Carolina');
INSERT INTO `sa_states` VALUES ('35', 'ND', 'North Dakota');
INSERT INTO `sa_states` VALUES ('36', 'OH', 'Ohio');
INSERT INTO `sa_states` VALUES ('37', 'OK', 'Oklahoma');
INSERT INTO `sa_states` VALUES ('38', 'OR', 'Oregon');
INSERT INTO `sa_states` VALUES ('39', 'PA', 'Pennsylvania');
INSERT INTO `sa_states` VALUES ('40', 'RI', 'Rhode Island');
INSERT INTO `sa_states` VALUES ('41', 'SC', 'South Carolina');
INSERT INTO `sa_states` VALUES ('42', 'SD', 'South Dakota');
INSERT INTO `sa_states` VALUES ('43', 'TN', 'Tennessee');
INSERT INTO `sa_states` VALUES ('44', 'TX', 'Texas');
INSERT INTO `sa_states` VALUES ('45', 'UT', 'Utah');
INSERT INTO `sa_states` VALUES ('46', 'VT', 'Vermont');
INSERT INTO `sa_states` VALUES ('47', 'VA', 'Virginia');
INSERT INTO `sa_states` VALUES ('48', 'WA', 'Washington');
INSERT INTO `sa_states` VALUES ('49', 'WV', 'West Virginia');
INSERT INTO `sa_states` VALUES ('50', 'WI', 'Wisconsin');
INSERT INTO `sa_states` VALUES ('51', 'WY', 'Wyoming');
